version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/nonprofit
      - JWT_SECRET=supersecret
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend